# Generated by Django 3.2.7 on 2021-09-05 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(default=datetime.date(1979, 8, 21)),
            preserve_default=False,
        ),
    ]
